### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by abrainc** [Gamma-Software/llm_qualitative_data_analysis#6]
I get this error when trying to run, I make not sure what I am doing wrong. I also made sure that my secrets file had no mistakes.

<img width="787" alt="Screenshot 2024-03-12 at 8 08 16 AM" src="https://github.com/Gamma-Software/llm_qualitative_data_analysis/assets/63295374/01138bfe-9212-4673-b684-1e3febd3cffa">

**Comment by Gamma-Software** [comment]
Hi @abrainc,
Here is a template:

```toml
[langchain]
debug = false

[langsmith]
tracing = "true"
api_url = "https://api.smith.langchain.com"
api_key = "key"
project = "qualitative_data_analysis"
```

You might have added the tracing value to this `tracing = true` instead of `tracing = "true"`
